apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: cm9vdA== # root en base64
  password: cGFzc3dvcmQ= # password en base64
  root-password: cm9vdHBhc3N3b3Jk # rootpassword en base64